export const browseActionTypes = {
  SET_CURRENT_WRAPPER: "SET_CURRENT_WRAPPER",
  FETCH_TOP_SONGS: "FETCH_TOP_SONGS",
  FETCH_TOP_SONGS_SUCCESS: "FETCH_TOP_SONGS_SUCCESS",
  FETCH_NEW_RELEASES: "FETCH_NEW_RELEASES",
  FETCH_NEW_RELEASES_SUCCESS: "FETCH_NEW_RELEASES_SUCCESS",
  FETCH_FEATURED_PLAYLISTS: "FETCH_FEATURED_PLAYLISTS",
  FETCH_FEATURED_PLAYLISTS_SUCCESS: "FETCH_FEATURED_PLAYLISTS_SUCCESS"
};
